# Generated by Django 6.0.1 on 2026-02-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartshopproduct',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='smartshopproduct',
            name='image_url',
        ),
        migrations.AddField(
            model_name='smartshopproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='smartshopproduct',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='smartshopproduct',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='smartshopproduct',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='smartshopproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
