# Generated by Django 6.0.1 on 2026-02-05 13:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshop', '0002_remove_smartshopproduct_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('ai_description', models.TextField(blank=True, help_text='Optional longer description for AI context (tone, target users, etc.).')),
            ],
        ),
        migrations.CreateModel(
            name='ShopUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text="External identifier, e.g. 'user_001'.", max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preference_profile', models.TextField(blank=True, help_text='Free-text summary of user preferences, brands they like, etc.')),
            ],
        ),
        migrations.AddField(
            model_name='smartshopproduct',
            name='ai_metadata',
            field=models.TextField(blank=True, help_text='Extra descriptive text for LLM analysis (who it’s for, pros/cons, etc.).'),
        ),
        migrations.AddField(
            model_name='smartshopproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartshopproduct',
            name='features',
            field=models.TextField(blank=True, help_text="Key features or tags, e.g. 'ergonomic, mesh back, adjustable height'."),
        ),
        migrations.AlterField(
            model_name='smartshopproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='smartshop.category'),
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('purchase', 'Purchase'), ('add_to_cart', 'Add to cart')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Optional 1–5 rating if applicable.', null=True)),
                ('review_text', models.TextField(blank=True, help_text='Optional free-text review or comment by the user.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='smartshop.smartshopproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='smartshop.shopuserprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
