# Generated by Django 6.0.1 on 2026-02-21 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshop', '0003_category_shopuserprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinteraction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='smartshopproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='smartshoppurchaseorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='product',
        ),
        migrations.RemoveField(
            model_name='category',
            name='ai_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('ai_description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='smartshop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='smartshop.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ShopUserProfile',
        ),
        migrations.DeleteModel(
            name='SmartShopPurchaseOrder',
        ),
        migrations.DeleteModel(
            name='SmartShopProduct',
        ),
        migrations.DeleteModel(
            name='UserInteraction',
        ),
    ]
